import { ViteMinifyPlugin as htmlminInstance } from 'vite-plugin-minify';

const htmlminConfig = {
  collapseWhitespace: true,
  includeAutoGeneratedTags: false,
  minifyCSS: true,
  minifyJS: true,
  removeComments: true,
};

const htmlmin = () => htmlminInstance(htmlminConfig);

export default htmlmin;
